In [16]:
import sys
sys.path.append('../src')

from extract import data_extract, DATA_URL

df = data_extract(DATA_URL)
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  str
 2   Sex     271116 non-null  str
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  str
 7   NOC     271116 non-null  str
 8   Games   271116 non-null  str
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  str
 11  City    271116 non-null  str
 12  Sport   271116 non-null  str
 13  Event   271116 non-null  str
 14  Medal   39783 non-null   str
dtypes: float64(3), int64(2), str(10)
memory usage: 31.0 MB

In [13]:
df.describe(include='all')

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
count,271116.000000,271116,271116,261642.000000,210945.000000,208241.000000,271116,271116,271116,271116.000000,271116,271116,271116,271116,39783
unique,NaN,134732,2,NaN,NaN,NaN,1184,230,51,NaN,2,42,66,765,3
top,NaN,Robert Tait McKenzie,M,NaN,NaN,NaN,United States,USA,2000 Summer,NaN,Summer,London,Athletics,Football Men's Football,Gold
freq,NaN,58,196594,NaN,NaN,NaN,17847,18853,13821,NaN,222552,22426,38624,5733,13372
mean,68248.954396,NaN,NaN,25.556898,175.338970,70.702393,NaN,NaN,NaN,1978.378480,NaN,NaN,NaN,NaN,NaN
std,39022.286345,NaN,NaN,6.393561,10.518462,14.348020,NaN,NaN,NaN,29.877632,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,10.000000,127.000000,25.000000,NaN,NaN,NaN,1896.000000,NaN,NaN,NaN,NaN,NaN
25%,34643.000000,NaN,NaN,21.000000,168.000000,60.000000,NaN,NaN,NaN,1960.000000,NaN,NaN,NaN,NaN,NaN
50%,68205.000000,NaN,NaN,24.000000,175.000000,70.000000,NaN,NaN,NaN,1988.000000,NaN,NaN,NaN,NaN,NaN
75%,102097.250000,NaN,NaN,28.000000,183.000000,79.000000,NaN,NaN,NaN,2002.000000,NaN,NaN,NaN,NaN,NaN
max,135571.000000,NaN,NaN,97.000000,226.000000,214.000000,NaN,NaN,NaN,2016.000000,NaN,NaN,NaN,NaN,NaN

In [10]:
# finding missing values
df.isnull().sum()

ID             0
Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     231333
dtype: int64

In [9]:
# finding missing values
df.isnull().mean() * 100

ID         0.000000
Name       0.000000
Sex        0.000000
Age        3.494445
Height    22.193821
Weight    23.191180
Team       0.000000
NOC        0.000000
Games      0.000000
Year       0.000000
Season     0.000000
City       0.000000
Sport      0.000000
Event      0.000000
Medal     85.326207
dtype: float64

In [14]:
for col in df.columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())

--- ID ---
ID
77710     58
106296    39
115354    38
119591    36
44875     32
          ..
135562     1
135564     1
135566     1
135568     1
135569     1
Name: count, Length: 135571, dtype: int64

--- Name ---
Name
Robert Tait McKenzie            58
Heikki Ilmari Savolainen        39
Joseph "Josy" Stoffel           38
Ioannis Theofilakis             36
Takashi Ono                     33
                                ..
Milan Zyka                       1
Yevgeny Aleksandrovich Zykov     1
James Francis "Jim" Zylker       1
Olga Igorevna Zyuzkova           1
Andrzej ya                       1
Name: count, Length: 134732, dtype: int64

--- Sex ---
Sex
M    196594
F     74522
Name: count, dtype: int64

--- Age ---
Age
23.0    21875
24.0    21720
22.0    20814
25.0    19707
21.0    19164
        ...
77.0        2
84.0        1
96.0        1
10.0        1
97.0        1
Name: count, Length: 74, dtype: int64

--- Height ---
Height
180.0    12492
170.0    11976
178.0    10708
175.0    10320
183.0     8284
         ...
226.0        3
131.0        2
130.0        2
219.0        2
128.0        1
Name: count, Length: 95, dtype: int64

--- Weight ---
Weight
70.0     9625
60.0     7994
75.0     7810
68.0     7284
65.0     7236
         ...
175.0       1
151.0       1
198.0       1
178.0       1
180.0       1
Name: count, Length: 220, dtype: int64

--- Team ---
Team
United States    17847
France           11988
Great Britain    11404
Italy            10260
Germany           9326
                 ...
Satchmo              1
Mainz                1
Solos Carex          1
Dow Jones            1
Digby                1
Name: count, Length: 1184, dtype: int64

--- NOC ---
NOC
USA    18853
FRA    12758
GBR    12256
ITA    10715
GER     9830
       ...
YMD        5
SSD        3
NBO        2
UNK        2
NFL        1
Name: count, Length: 230, dtype: int64

--- Games ---
Games
2000 Summer    13821
1996 Summer    13780
2016 Summer    13688
2008 Summer    13602
2004 Summer    13443
1992 Summer    12977
2012 Summer    12920
1988 Summer    12037
1972 Summer    10304
1984 Summer     9454
1976 Summer     8641
1968 Summer     8588
1952 Summer     8270
1960 Summer     8119
1964 Summer     7702
1980 Summer     7191
1936 Summer     6506
1948 Summer     6405
1924 Summer     5233
1956 Summer     5127
1928 Summer     4992
2014 Winter     4891
2010 Winter     4402
2006 Winter     4382
1920 Summer     4292
2002 Winter     4109
1912 Summer     4040
1998 Winter     3605
1992 Winter     3436
1994 Winter     3160
1908 Summer     3101
1932 Summer     2969
1988 Winter     2639
1984 Winter     2134
1900 Summer     1936
1968 Winter     1891
1976 Winter     1861
1964 Winter     1778
1980 Winter     1746
1906 Summer     1733
1972 Winter     1655
1956 Winter     1307
1904 Summer     1301
1960 Winter     1116
1952 Winter     1088
1948 Winter     1075
1936 Winter      895
1928 Winter      582
1924 Winter      460
1896 Summer      380
1932 Winter      352
Name: count, dtype: int64

--- Year ---
Year
1992    16413
1988    14676
2000    13821
1996    13780
2016    13688
2008    13602
2004    13443
2012    12920
1972    11959
1984    11588
1976    10502
1968    10479
1964     9480
1952     9358
1960     9235
1980     8937
1948     7480
1936     7401
1956     6434
1924     5693
1928     5574
2014     4891
2010     4402
2006     4382
1920     4292
2002     4109
1912     4040
1998     3605
1932     3321
1994     3160
1908     3101
1900     1936
1906     1733
1904     1301
1896      380
Name: count, dtype: int64

--- Season ---
Season
Summer    222552
Winter     48564
Name: count, dtype: int64

--- City ---
City
London                    22426
Athina                    15556
Sydney                    13821
Atlanta                   13780
Rio de Janeiro            13688
Beijing                   13602
Barcelona                 12977
Los Angeles               12423
Seoul                     12037
Munich                    10304
Montreal                   8641
Mexico City                8588
Helsinki                   8270
Roma                       8119
Tokyo                      7702
Moskva                     7191
Paris                      7169
Berlin                     6506
Amsterdam                  4992
Sochi                      4891
Melbourne                  4829
Vancouver                  4402
Torino                     4382
Stockholm                  4338
Antwerpen                  4292
Salt Lake City             4109
Innsbruck                  3639
Nagano                     3605
Albertville                3436
Lillehammer                3160
Calgary                    2639
Sarajevo                   2134
Lake Placid                2098
Grenoble                   1891
Sankt Moritz               1657
Sapporo                    1655
Cortina d'Ampezzo          1307
St. Louis                  1301
Squaw Valley               1116
Oslo                       1088
Garmisch-Partenkirchen      895
Chamonix                    460
Name: count, dtype: int64

--- Sport ---
Sport
Athletics        38624
Gymnastics       26707
Swimming         23195
Shooting         11448
Cycling          10859
                 ...
Racquets            12
Jeu De Paume        11
Roque                4
Basque Pelota        2
Aeronautics          1
Name: count, Length: 66, dtype: int64

--- Event ---
Event
Football Men's Football                                5733
Ice Hockey Men's Ice Hockey                            4762
Hockey Men's Hockey                                    3958
Water Polo Men's Water Polo                            3358
Basketball Men's Basketball                            3280
                                                       ...
Basque Pelota Men's Two-Man Teams With Cesta              2
Sailing Mixed 18 foot                                     2
Archery Men's Championnat Du Monde                        2
Archery Men's Target Archery, 28 metres, Individual       2
Aeronautics Mixed Aeronautics                             1
Name: count, Length: 765, dtype: int64

--- Medal ---
Medal
Gold      13372
Bronze    13295
Silver    13116
Name: count, dtype: int64

In [18]:
df_age_female = (df[df['Sex'] == "F"])['Age'].mean()
df_age_male = (df[df['Sex'] == "M"])['Age'].mean()
print(df_age_female)
print(df_age_male)

23.732880779508218
26.277561532227104

In [19]:
# Überblick
df.info()           # Datentypen, null values
df.describe()       # Statistiken
df.shape            # Anzahl Zeilen und Spalten

# Null values
df.isnull().sum()

# Duplikate
df.duplicated().sum()

# Unique values pro Spalte
df.nunique()

<class 'pandas.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  str
 2   Sex     271116 non-null  str
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  str
 7   NOC     271116 non-null  str
 8   Games   271116 non-null  str
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  str
 11  City    271116 non-null  str
 12  Sport   271116 non-null  str
 13  Event   271116 non-null  str
 14  Medal   39783 non-null   str
dtypes: float64(3), int64(2), str(10)
memory usage: 31.0 MB

ID        135571
Name      134732
Sex            2
Age           74
Height        95
Weight       220
Team        1184
NOC          230
Games         51
Year          35
Season         2
City          42
Sport         66
Event        765
Medal          3
dtype: int64